
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.itsalldoors.init;

import net.minecraft.world.level.block.Block;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.mcreator.itsalldoors.block.WarpednyliumsidedoorBlock;
import net.mcreator.itsalldoors.block.StonedoorBlock;
import net.mcreator.itsalldoors.block.StonebricksdoorBlock;
import net.mcreator.itsalldoors.block.SprucelogdoorBlock;
import net.mcreator.itsalldoors.block.SmoothstoneslabsidedoorBlock;
import net.mcreator.itsalldoors.block.SmoothstonedoorBlock;
import net.mcreator.itsalldoors.block.RednetherbricksdoorBlock;
import net.mcreator.itsalldoors.block.PreciousdoorBlock;
import net.mcreator.itsalldoors.block.PolishedblackstonebricksdoorBlock;
import net.mcreator.itsalldoors.block.OaklogdoorBlock;
import net.mcreator.itsalldoors.block.NetherrackdoorBlock;
import net.mcreator.itsalldoors.block.NetherquartzdoorBlock;
import net.mcreator.itsalldoors.block.NetherquartzandgolddoorBlock;
import net.mcreator.itsalldoors.block.NetheritedoorBlock;
import net.mcreator.itsalldoors.block.NethergolddoorBlock;
import net.mcreator.itsalldoors.block.NethergoldandquartzdoorBlock;
import net.mcreator.itsalldoors.block.NetherbricksdoorBlock;
import net.mcreator.itsalldoors.block.MudbricksdoorBlock;
import net.mcreator.itsalldoors.block.MossystonebricksdoorBlock;
import net.mcreator.itsalldoors.block.MossycobblestonedoorBlock;
import net.mcreator.itsalldoors.block.MangrovelogdoorBlock;
import net.mcreator.itsalldoors.block.JunglelogdoorBlock;
import net.mcreator.itsalldoors.block.EndstonedoorBlock;
import net.mcreator.itsalldoors.block.EndstonebricksdoorBlock;
import net.mcreator.itsalldoors.block.DeepslatebricksdoorBlock;
import net.mcreator.itsalldoors.block.DarkoaklogdoorBlock;
import net.mcreator.itsalldoors.block.CrimsonnyliumsidedoorBlock;
import net.mcreator.itsalldoors.block.CrackedstonebricksdoorBlock;
import net.mcreator.itsalldoors.block.CrackedpolishedblackstonebricksdoorBlock;
import net.mcreator.itsalldoors.block.CrackednetherbricksdoorBlock;
import net.mcreator.itsalldoors.block.CrackeddeepslatebricksdoorBlock;
import net.mcreator.itsalldoors.block.CobblestonedoorBlock;
import net.mcreator.itsalldoors.block.CobbleddeepslatedoorBlock;
import net.mcreator.itsalldoors.block.ChiseledstonebricksdoorBlock;
import net.mcreator.itsalldoors.block.ChiseledpolishedblackstonedoorBlock;
import net.mcreator.itsalldoors.block.ChiselednetherbricksdoorBlock;
import net.mcreator.itsalldoors.block.CherrylogdoorBlock;
import net.mcreator.itsalldoors.block.BrichlogdoorBlock;
import net.mcreator.itsalldoors.block.AcacialogdoorBlock;
import net.mcreator.itsalldoors.ItsAllDoorsMod;

public class ItsAllDoorsModBlocks {
	public static Block BRICHLOGDOOR;
	public static Block OAKLOGDOOR;
	public static Block ACACIALOGDOOR;
	public static Block DARKOAKLOGDOOR;
	public static Block SPRUCELOGDOOR;
	public static Block JUNGLELOGDOOR;
	public static Block MANGROVELOGDOOR;
	public static Block CHERRYLOGDOOR;
	public static Block STONEDOOR;
	public static Block STONEBRICKSDOOR;
	public static Block CRACKEDSTONEBRICKSDOOR;
	public static Block MOSSYSTONEBRICKSDOOR;
	public static Block CHISELEDSTONEBRICKSDOOR;
	public static Block SMOOTHSTONEDOOR;
	public static Block SMOOTHSTONESLABSIDEDOOR;
	public static Block ENDSTONEDOOR;
	public static Block ENDSTONEBRICKSDOOR;
	public static Block CHISELEDPOLISHEDBLACKSTONEDOOR;
	public static Block COBBLESTONEDOOR;
	public static Block MOSSYCOBBLESTONEDOOR;
	public static Block COBBLEDDEEPSLATEDOOR;
	public static Block CRIMSONNYLIUMSIDEDOOR;
	public static Block WARPEDNYLIUMSIDEDOOR;
	public static Block NETHERRACKDOOR;
	public static Block NETHERGOLDDOOR;
	public static Block NETHERQUARTZDOOR;
	public static Block NETHERQUARTZANDGOLDDOOR;
	public static Block NETHERGOLDANDQUARTZDOOR;
	public static Block NETHERITEDOOR;
	public static Block CHISELEDNETHERBRICKSDOOR;
	public static Block NETHERBRICKSDOOR;
	public static Block CRACKEDNETHERBRICKSDOOR;
	public static Block REDNETHERBRICKSDOOR;
	public static Block PRECIOUSDOOR;
	public static Block MUDBRICKSDOOR;
	public static Block DEEPSLATEBRICKSDOOR;
	public static Block CRACKEDDEEPSLATEBRICKSDOOR;
	public static Block POLISHEDBLACKSTONEBRICKSDOOR;
	public static Block CRACKEDPOLISHEDBLACKSTONEBRICKSDOOR;

	public static void load() {
		BRICHLOGDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "brichlogdoor"), new BrichlogdoorBlock());
		OAKLOGDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "oaklogdoor"), new OaklogdoorBlock());
		ACACIALOGDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "acacialogdoor"), new AcacialogdoorBlock());
		DARKOAKLOGDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "darkoaklogdoor"), new DarkoaklogdoorBlock());
		SPRUCELOGDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "sprucelogdoor"), new SprucelogdoorBlock());
		JUNGLELOGDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "junglelogdoor"), new JunglelogdoorBlock());
		MANGROVELOGDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "mangrovelogdoor"), new MangrovelogdoorBlock());
		CHERRYLOGDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "cherrylogdoor"), new CherrylogdoorBlock());
		STONEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "stonedoor"), new StonedoorBlock());
		STONEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "stonebricksdoor"), new StonebricksdoorBlock());
		CRACKEDSTONEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "crackedstonebricksdoor"), new CrackedstonebricksdoorBlock());
		MOSSYSTONEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "mossystonebricksdoor"), new MossystonebricksdoorBlock());
		CHISELEDSTONEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "chiseledstonebricksdoor"), new ChiseledstonebricksdoorBlock());
		SMOOTHSTONEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "smoothstonedoor"), new SmoothstonedoorBlock());
		SMOOTHSTONESLABSIDEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "smoothstoneslabsidedoor"), new SmoothstoneslabsidedoorBlock());
		ENDSTONEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "endstonedoor"), new EndstonedoorBlock());
		ENDSTONEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "endstonebricksdoor"), new EndstonebricksdoorBlock());
		CHISELEDPOLISHEDBLACKSTONEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "chiseledpolishedblackstonedoor"), new ChiseledpolishedblackstonedoorBlock());
		COBBLESTONEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "cobblestonedoor"), new CobblestonedoorBlock());
		MOSSYCOBBLESTONEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "mossycobblestonedoor"), new MossycobblestonedoorBlock());
		COBBLEDDEEPSLATEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "cobbleddeepslatedoor"), new CobbleddeepslatedoorBlock());
		CRIMSONNYLIUMSIDEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "crimsonnyliumsidedoor"), new CrimsonnyliumsidedoorBlock());
		WARPEDNYLIUMSIDEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "warpednyliumsidedoor"), new WarpednyliumsidedoorBlock());
		NETHERRACKDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "netherrackdoor"), new NetherrackdoorBlock());
		NETHERGOLDDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "nethergolddoor"), new NethergolddoorBlock());
		NETHERQUARTZDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "netherquartzdoor"), new NetherquartzdoorBlock());
		NETHERQUARTZANDGOLDDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "netherquartzandgolddoor"), new NetherquartzandgolddoorBlock());
		NETHERGOLDANDQUARTZDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "nethergoldandquartzdoor"), new NethergoldandquartzdoorBlock());
		NETHERITEDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "netheritedoor"), new NetheritedoorBlock());
		CHISELEDNETHERBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "chiselednetherbricksdoor"), new ChiselednetherbricksdoorBlock());
		NETHERBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "netherbricksdoor"), new NetherbricksdoorBlock());
		CRACKEDNETHERBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "crackednetherbricksdoor"), new CrackednetherbricksdoorBlock());
		REDNETHERBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "rednetherbricksdoor"), new RednetherbricksdoorBlock());
		PRECIOUSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "preciousdoor"), new PreciousdoorBlock());
		MUDBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "mudbricksdoor"), new MudbricksdoorBlock());
		DEEPSLATEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "deepslatebricksdoor"), new DeepslatebricksdoorBlock());
		CRACKEDDEEPSLATEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "crackeddeepslatebricksdoor"), new CrackeddeepslatebricksdoorBlock());
		POLISHEDBLACKSTONEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "polishedblackstonebricksdoor"), new PolishedblackstonebricksdoorBlock());
		CRACKEDPOLISHEDBLACKSTONEBRICKSDOOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(ItsAllDoorsMod.MODID, "crackedpolishedblackstonebricksdoor"), new CrackedpolishedblackstonebricksdoorBlock());
	}

	public static void clientLoad() {
		BrichlogdoorBlock.clientInit();
		OaklogdoorBlock.clientInit();
		AcacialogdoorBlock.clientInit();
		DarkoaklogdoorBlock.clientInit();
		SprucelogdoorBlock.clientInit();
		JunglelogdoorBlock.clientInit();
		MangrovelogdoorBlock.clientInit();
		CherrylogdoorBlock.clientInit();
		StonedoorBlock.clientInit();
		StonebricksdoorBlock.clientInit();
		CrackedstonebricksdoorBlock.clientInit();
		MossystonebricksdoorBlock.clientInit();
		ChiseledstonebricksdoorBlock.clientInit();
		SmoothstonedoorBlock.clientInit();
		SmoothstoneslabsidedoorBlock.clientInit();
		EndstonedoorBlock.clientInit();
		EndstonebricksdoorBlock.clientInit();
		ChiseledpolishedblackstonedoorBlock.clientInit();
		CobblestonedoorBlock.clientInit();
		MossycobblestonedoorBlock.clientInit();
		CobbleddeepslatedoorBlock.clientInit();
		CrimsonnyliumsidedoorBlock.clientInit();
		WarpednyliumsidedoorBlock.clientInit();
		NetherrackdoorBlock.clientInit();
		NethergolddoorBlock.clientInit();
		NetherquartzdoorBlock.clientInit();
		NetherquartzandgolddoorBlock.clientInit();
		NethergoldandquartzdoorBlock.clientInit();
		NetheritedoorBlock.clientInit();
		ChiselednetherbricksdoorBlock.clientInit();
		NetherbricksdoorBlock.clientInit();
		CrackednetherbricksdoorBlock.clientInit();
		RednetherbricksdoorBlock.clientInit();
		PreciousdoorBlock.clientInit();
		MudbricksdoorBlock.clientInit();
		DeepslatebricksdoorBlock.clientInit();
		CrackeddeepslatebricksdoorBlock.clientInit();
		PolishedblackstonebricksdoorBlock.clientInit();
		CrackedpolishedblackstonebricksdoorBlock.clientInit();
	}
}
